# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='full_name',
            field=models.CharField(default='Joe Doe', max_length=30),
            preserve_default=False,
        ),
    ]
