# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0003_auto_20170901_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='duration_of_reception',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
